[package]
name = "ip-juggler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.8"
once_cell = "1.13"
pnet = "0.30.0"
regex = "1"
